### ISSUE TITLE
2章 字句構造

### ISSUE THREAD

**Issue by myuon** [myuon/haskell2010-ja#1]

**Comment by tositeru** [comment]
2章の翻訳が終わったのですが、マージするときはForkしてPullRequestする感じでしょうか？

**Comment by tositeru** [comment]
とりあえず、ForkしたものでPullRequestを送りました。レビューのほどお願いします。

**Comment by myuon** [comment]
ありがとうございます！現時点ではそのようなフローで問題ありません。

**Comment by myuon** [comment]
一通り終わったのでクローズ
