### ISSUE TITLE
共通のCSSファイルの作成 () 

### ISSUE THREAD

**Issue by tositeru** [myuon/haskell2010-ja#19]
3章を翻訳中、境界線で囲まれた文章を見つけました。

cssで境界線を指定すれば解決すると思いますが、適当にcssファイルを追加してしまうと色々混乱の元となると思われるので、共通のcssファイルがあればいいと思うのですがどうでしょうか？

**Comment by myuon** [comment]
賛成です、やり方調べときます(一旦分かるようにしておいてもらえれば)

多分これ https://github.com/rust-lang-nursery/mdBook/issues/178

**Comment by tositeru** [comment]
mdbookのthemeを使って、好きなcss要素を追加できるようにしました。

ルートディレクトリにthemeディレクトリを追加しcss/general.cssを編集することで実現しています。
[mdBook Theme](http://rust-lang-nursery.github.io/mdBook/format/theme/index.html)

book.tomlにadditional-cssを指定してあげると、好きなcss/jsファイルを追加できるようです。
(additional-cssは[output.html]の下に書かないといけない)
[mdBook Configuration](http://rust-lang-nursery.github.io/mdBook/format/config.html)

が、生成されたhtml内のCSSファイルパスがbook.tomlで指定したパスそのまま出力されており、ビルド出力先のディレクトリ階層は考慮されていないようです。
([次のリリースでは解決されるとかないとかissue](https://github.com/rust-lang-nursery/mdBook/pull/777)にありましたが… ちなみにこちらのmdbookのバージョンはv0.2.1です)

**Comment by myuon** [comment]
0.2.2のタグ自体は打たれてますけどリリースっていつなんでしょうね(去年の9月からリリースされてないっぽい？)
最悪0.2.2使うのもありですかねぇ
https://github.com/rust-lang-nursery/mdBook/releases/tag/v0.2.2

**Comment by tositeru** [comment]
開発環境はLinuxの方がよろしいでしょうか？

こちらWindow環境下でcargoからmdbookをインストールしたところutf-8パッケージでビルドエラーが出て、v0.2.1で動かしている感じです。

v0.2.2では確認していません。

**Comment by myuon** [comment]
私はWindows上でWSL使ってます(WSLでは一応v0.2.2入りました)。
単純にmdbook側のバグであればissueとして報告してもよいかなと思います。動く目途が立つなら0.2.2使い始めてもいいんですが、そうでないなら0.2.1で動くworkaroundを探した方がいいかもしれないですね…

**Comment by myuon** [comment]
生成されたHTML見る限り大丈夫そうなのでOKということで
