### ISSUE TITLE
用語集の作成

### ISSUE THREAD

**Issue by myuon** [myuon/haskell2010-ja#27]
単語の表記ブレ等をなくしたいので用語集を作りたい
wikiにどんどん載せていく感じでいいか？

**Comment by tositeru** [comment]
OKです。

**Comment by myuon** [comment]
(一緒にレビューするという観点からはリポジトリに直接含めたほうがいいような気がしてきた…)

**Comment by tositeru** [comment]
賛成です。ローカルで見れる便利ですよね。

ただ、リポジトリに入れると修正したときに他のブランチに適応する手間が出てくるので、Wikiと併用した方がいいかと思います。

**Comment by myuon** [comment]
@tositeru やっぱり用語集もレビュー通したいのでPR送ってもらえますか？
用語集はリポジトリに含めて、ただし用語集へのコミットは例えば `glossary` branchでのみ行い、通常の訳のPRとは分けるなどでコンフリクトには対処したいです。

**Comment by myuon** [comment]
一般用語と専門用語、区別が曖昧すぎるので分ける意味ない気もしてきた
一旦章ごとに分けたいところ

**Comment by tositeru** [comment]
了解です。

glossaryディレクトリを新しく作って、chapter-XX.mdってな感じでファイルを作っていきますね。
とりあえず、2,3,4章をこちらでやっていきます。

**Comment by myuon** [comment]
ありがとうございます :pray: 
そんな感じでお願いします 2,3,4できたらPR送ってもらえれば :ok_hand:

**Comment by myuon** [comment]
あと、章ごとに単語を分けるのであれば、今後は章の翻訳とglossaryへの追加を同じPRでやってもらう方がいいかと思います

**Comment by myuon** [comment]
一通り翻訳終わったらまた一覧を作りたいところ
