### ISSUE TITLE
ttタグのスタイルを追加したい。

### ISSUE THREAD

**Issue by tositeru** [myuon/haskell2010-ja#34]
終端記号にttタグを付けていますが、フォントや文字サイズが他のものと同じになっているので、
CSSで専用のスタイルを指定したいのですが、いいでしょうか？

フォントは原文と同じ。DejaVu Sans Monoを使い
サイズも原文のものと同じ12pxを指定する予定ですが、こちらは目で見ていい感じになるようにするつもりです。

**Comment by myuon** [comment]
構いませんがフォントは環境に依存してしまうので無理に指定する必要はないと思います
薄く背景色を付けるとかしたいですね

**Comment by tositeru** [comment]
了解です！
